# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0294ece84272ac39ccfc888b4723b86af7852095f39c55b5605205871cfe781f6c6441f71ffc35df3be3f826998b89b1d4a60968428d75e2fdad0ca064bb0a1f

test:
  secret_key_base: f9742ed54922feaecfe753b0f6a2501942a3b2df5735ee03f91d6a5b165120fb178a482e371b3c176ed650de17574cc634b716fcedc201eb32f26b2adb3d79b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
